In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import pandas as pd
import numpy as np


In [3]:
mat_file_path = '/content/drive/MyDrive/CSE_250A_final_project/data_processing/student-mat.csv'
mat_df = pd.read_csv(mat_file_path, sep=';')
display(mat_df.head())

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [4]:
por_file_path = '/content/drive/MyDrive/CSE_250A_final_project/data_processing/student-por.csv'
por_df = pd.read_csv(por_file_path, sep=';')
display(por_df.head())

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        4   0  11  11  
1      5        3      3     1     1      3        2   9  11  11  
2      4        3      2     2     3      3        6  12  13  12  
3      3        2      2     1     1      5        0  14  14  14  
4      4        3      2     1     2      5        0  11  13  13  

[5 rows x 33 columns]

Ignoring (because we found the additional note that 382 students belong to both datasets)


In [5]:
print('Columns of mat_df:')
display(mat_df.columns)
display(len(mat_df.columns))
print('\nColumns of por_df:')
display(por_df.columns)

Columns of mat_df:


Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

33


Columns of por_df:


Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [6]:
print('Unique values in mat_df["school"]:')
display(mat_df['school'].unique())

print('\nUnique values in por_df["school"]:')
display(por_df['school'].unique())

Unique values in mat_df["school"]:


array(['GP', 'MS'], dtype=object)


Unique values in por_df["school"]:


array(['GP', 'MS'], dtype=object)

In [7]:
mat_df_processed = mat_df.copy()
por_df_processed = por_df.copy()

#'yes'/'no' columns
def map_yes_no(df, column_name):
    df[column_name] = df[column_name].map({'no': 0, 'yes': 1})
    return df

# 'sex' col: 'F' -> 0, 'M' -> 1
mat_df_processed['sex'] = mat_df_processed['sex'].map({'F': 0, 'M': 1})
por_df_processed['sex'] = por_df_processed['sex'].map({'F': 0, 'M': 1})

# 'address' col: 'U' (urban) -> 0, 'R' (rural) -> 1
mat_df_processed['address'] = mat_df_processed['address'].map({'U': 0, 'R': 1})
por_df_processed['address'] = por_df_processed['address'].map({'U': 0, 'R': 1})

# 'famsize' col: 'LE3' (less or equal to 3) -> 0, 'GT3' (greater than 3) -> 1
mat_df_processed['famsize'] = mat_df_processed['famsize'].map({'LE3': 0, 'GT3': 1})
por_df_processed['famsize'] = por_df_processed['famsize'].map({'LE3': 0, 'GT3': 1})

# 'Pstatus' col: 'A' (apart) -> 0, 'T' (together) -> 1
mat_df_processed['Pstatus'] = mat_df_processed['Pstatus'].map({'A': 0, 'T': 1})
por_df_processed['Pstatus'] = por_df_processed['Pstatus'].map({'A': 0, 'T': 1})

# 'school' col: 'GP' -> 0, 'MS' -> 1
mat_df_processed['school'] = mat_df_processed['school'].map({'GP': 0, 'MS': 1})
por_df_processed['school'] = por_df_processed['school'].map({'GP': 0, 'MS': 1})

# 'yes'/'no' cols
yes_no_columns = [
    'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
    'higher', 'internet', 'romantic'
]

for col in yes_no_columns:
    mat_df_processed = map_yes_no(mat_df_processed, col)
    por_df_processed = map_yes_no(por_df_processed, col)

display(mat_df_processed.head())
display(por_df_processed.head())

school  sex  age  address  famsize  Pstatus  Medu  Fedu     Mjob      Fjob  \
0       0    0   18        0        1        0     4     4  at_home   teacher   
1       0    0   17        0        1        1     1     1  at_home     other   
2       0    0   15        0        0        1     1     1  at_home     other   
3       0    0   15        0        1        1     4     2   health  services   
4       0    0   16        0        1        1     3     3    other     other   

   ... famrel freetime  goout  Dalc  Walc  health  absences  G1  G2  G3  
0  ...      4        3      4     1     1       3         6   5   6   6  
1  ...      5        3      3     1     1       3         4   5   5   6  
2  ...      4        3      2     2     3       3        10   7   8  10  
3  ...      3        2      2     1     1       5         2  15  14  15  
4  ...      4        3      2     1     2       5         4   6  10  10  

[5 rows x 33 columns]

school  sex  age  address  famsize  Pstatus  Medu  Fedu     Mjob      Fjob  \
0       0    0   18        0        1        0     4     4  at_home   teacher   
1       0    0   17        0        1        1     1     1  at_home     other   
2       0    0   15        0        0        1     1     1  at_home     other   
3       0    0   15        0        1        1     4     2   health  services   
4       0    0   16        0        1        1     3     3    other     other   

   ... famrel freetime  goout  Dalc  Walc  health  absences  G1  G2  G3  
0  ...      4        3      4     1     1       3         4   0  11  11  
1  ...      5        3      3     1     1       3         2   9  11  11  
2  ...      4        3      2     2     3       3         6  12  13  12  
3  ...      3        2      2     1     1       5         0  14  14  14  
4  ...      4        3      2     1     2       5         0  11  13  13  

[5 rows x 33 columns]

In [8]:
print('mat_df_processed binary columns: \n')

binary_columns_to_check = [
    'school', 'sex', 'address', 'famsize', 'Pstatus',
    'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
    'higher', 'internet', 'romantic'
]

for col in binary_columns_to_check:
    if col in mat_df_processed.columns:
        print(f"Unique values for '{col}' in mat_df_processed: ")
        display(mat_df_processed[col].unique())
    else:
        print(f"Column '{col}' not found in mat_df_processed.")

print('por_df_processed binary columns: \n')
for col in binary_columns_to_check:
    if col in por_df_processed.columns:
        print(f"Unique values for '{col}' in por_df_processed: ")
        display(por_df_processed[col].unique())
    else:
        print(f"Column '{col}' not found in por_df_processed.")

mat_df_processed binary columns: 

Unique values for 'school' in mat_df_processed: 


array([0, 1])

Unique values for 'sex' in mat_df_processed: 


array([0, 1])

Unique values for 'address' in mat_df_processed: 


array([0, 1])

Unique values for 'famsize' in mat_df_processed: 


array([1, 0])

Unique values for 'Pstatus' in mat_df_processed: 


array([0, 1])

Unique values for 'schoolsup' in mat_df_processed: 


array([1, 0])

Unique values for 'famsup' in mat_df_processed: 


array([0, 1])

Unique values for 'paid' in mat_df_processed: 


array([0, 1])

Unique values for 'activities' in mat_df_processed: 


array([0, 1])

Unique values for 'nursery' in mat_df_processed: 


array([1, 0])

Unique values for 'higher' in mat_df_processed: 


array([1, 0])

Unique values for 'internet' in mat_df_processed: 


array([0, 1])

Unique values for 'romantic' in mat_df_processed: 


array([0, 1])

por_df_processed binary columns: 

Unique values for 'school' in por_df_processed: 


array([0, 1])

Unique values for 'sex' in por_df_processed: 


array([0, 1])

Unique values for 'address' in por_df_processed: 


array([0, 1])

Unique values for 'famsize' in por_df_processed: 


array([1, 0])

Unique values for 'Pstatus' in por_df_processed: 


array([0, 1])

Unique values for 'schoolsup' in por_df_processed: 


array([1, 0])

Unique values for 'famsup' in por_df_processed: 


array([0, 1])

Unique values for 'paid' in por_df_processed: 


array([0, 1])

Unique values for 'activities' in por_df_processed: 


array([0, 1])

Unique values for 'nursery' in por_df_processed: 


array([1, 0])

Unique values for 'higher' in por_df_processed: 


array([1, 0])

Unique values for 'internet' in por_df_processed: 


array([0, 1])

Unique values for 'romantic' in por_df_processed: 


array([0, 1])

In [9]:
display(mat_df_processed['age'].unique())
display(mat_df_processed['Medu'].unique())
display(mat_df_processed['Fedu'].unique())
display(mat_df_processed['traveltime'].unique())
display(mat_df_processed['studytime'].unique())
display(mat_df_processed['failures'].unique())
display(mat_df_processed['famrel'].unique())
display(mat_df_processed['freetime'].unique())
display(mat_df_processed['goout'].unique())
display(mat_df_processed['Dalc'].unique())
display(mat_df_processed['Walc'].unique())
display(mat_df_processed['health'].unique())
display(mat_df_processed['absences'].unique())


array([18, 17, 15, 16, 19, 22, 20, 21])

array([4, 1, 3, 2, 0])

array([4, 1, 2, 3, 0])

array([2, 1, 3, 4])

array([2, 3, 1, 4])

array([0, 3, 2, 1])

array([4, 5, 3, 1, 2])

array([3, 2, 4, 1, 5])

array([4, 3, 2, 1, 5])

array([1, 2, 5, 3, 4])

array([1, 3, 2, 4, 5])

array([3, 5, 1, 2, 4])

array([ 6,  4, 10,  2,  0, 16, 14,  7,  8, 25, 12, 54, 18, 26, 20, 56, 24,
       28,  5, 13, 15, 22,  3, 21,  1, 75, 30, 19,  9, 11, 38, 40, 23, 17])

In [10]:
# Ages: 15-17 -> 0 (high school age), 18-22 -> 1 (college/uni age)
age_bins = [14, 17, 22] # Using 14 as lower bound to include 15, 22 as upper bound to include 22
age_labels = [0, 1]

mat_df_processed['age_category'] = pd.cut(mat_df_processed['age'], bins=age_bins, labels=age_labels, right=True, include_lowest=True)
por_df_processed['age_category'] = pd.cut(por_df_processed['age'], bins=age_bins, labels=age_labels, right=True, include_lowest=True)

# Fail (0-9) -> 0, Pass (10-14) -> 1, Good (15-20) -> 2
grade_bins = [-1, 9, 14, 20] # Using -1 to include 0, and 20 for upper bound
grade_labels = [0, 1, 2]

for col in ['G1', 'G2', 'G3']:
    mat_df_processed[f'{col}_category'] = pd.cut(mat_df_processed[col], bins=grade_bins, labels=grade_labels, right=True, include_lowest=True)
    por_df_processed[f'{col}_category'] = pd.cut(por_df_processed[col], bins=grade_bins, labels=grade_labels, right=True, include_lowest=True)

# None (0) -> 0, Low (1-5) -> 1, Medium (6-15) -> 2, High (16+) -> 3
# Using max absences to set the upper bound for 'High'
max_absences = max(mat_df_processed['absences'].max(), por_df_processed['absences'].max())
absences_bins = [-1, 0, 5, 15, max_absences]
absences_labels = [0, 1, 2, 3]

mat_df_processed['absences_category'] = pd.cut(mat_df_processed['absences'], bins=absences_bins, labels=absences_labels, right=True, include_lowest=True)
por_df_processed['absences_category'] = pd.cut(por_df_processed['absences'], bins=absences_bins, labels=absences_labels, right=True, include_lowest=True)

print("mat_df_processed with new categorized columns:")
display(mat_df_processed[['age', 'age_category', 'G1', 'G1_category', 'absences', 'absences_category']].head())

print("\npor_df_processed with new categorized columns:")
display(por_df_processed[['age', 'age_category', 'G1', 'G1_category', 'absences', 'absences_category']].head())

mat_df_processed with new categorized columns:


age age_category  G1 G1_category  absences absences_category
0   18            1   5           0         6                 2
1   17            0   5           0         4                 1
2   15            0   7           0        10                 2
3   15            0  15           2         2                 1
4   16            0   6           0         4                 1


por_df_processed with new categorized columns:


age age_category  G1 G1_category  absences absences_category
0   18            1   0           0         4                 1
1   17            0   9           0         2                 1
2   15            0  12           1         6                 2
3   15            0  14           1         0                 0
4   16            0  11           1         0                 0

In [11]:
mat_df_processed.head()
# +5 columns for bins category

school  sex  age  address  famsize  Pstatus  Medu  Fedu     Mjob      Fjob  \
0       0    0   18        0        1        0     4     4  at_home   teacher   
1       0    0   17        0        1        1     1     1  at_home     other   
2       0    0   15        0        0        1     1     1  at_home     other   
3       0    0   15        0        1        1     4     2   health  services   
4       0    0   16        0        1        1     3     3    other     other   

   ... health absences  G1  G2  G3  age_category  G1_category  G2_category  \
0  ...      3        6   5   6   6             1            0            0   
1  ...      3        4   5   5   6             0            0            0   
2  ...      3       10   7   8  10             0            0            0   
3  ...      5        2  15  14  15             0            2            1   
4  ...      5        4   6  10  10             0            0            1   

   G3_category  absences_category  
0            0                  2  
1            0                  1  
2            1                  2  
3            2                  1  
4            1                  1  

[5 rows x 38 columns]

In [12]:
# columns to drop (original numeric columns that have been categorized)
columns_to_drop_originals = ['age', 'G1', 'G2', 'G3', 'absences']

original_mat_df_columns = mat_df.columns.tolist()
original_por_df_columns = por_df.columns.tolist()

final_mat_columns_ordered = []
for col in original_mat_df_columns:
    if col in columns_to_drop_originals:
        final_mat_columns_ordered.append(f'{col}_category')
    else:
        final_mat_columns_ordered.append(col)

final_por_columns_ordered = []
for col in original_por_df_columns:
    if col in columns_to_drop_originals:
        final_por_columns_ordered.append(f'{col}_category')
    else:
        final_por_columns_ordered.append(col)

mat_df_final = mat_df_processed[final_mat_columns_ordered].copy()
por_df_final = por_df_processed[final_por_columns_ordered].copy()

print("mat_df_final columns:", len(mat_df_final.columns))
display(mat_df_final.head())

print("\npor_df_final columns:", len(por_df_final.columns))
display(por_df_final.head())

mat_df_final columns: 33


school  sex age_category  address  famsize  Pstatus  Medu  Fedu     Mjob  \
0       0    0            1        0        1        0     4     4  at_home   
1       0    0            0        0        1        1     1     1  at_home   
2       0    0            0        0        0        1     1     1  at_home   
3       0    0            0        0        1        1     4     2   health   
4       0    0            0        0        1        1     3     3    other   

       Fjob  ... famrel freetime  goout  Dalc  Walc  health  \
0   teacher  ...      4        3      4     1     1       3   
1     other  ...      5        3      3     1     1       3   
2     other  ...      4        3      2     2     3       3   
3  services  ...      3        2      2     1     1       5   
4     other  ...      4        3      2     1     2       5   

   absences_category  G1_category  G2_category  G3_category  
0                  2            0            0            0  
1                  1            0            0            0  
2                  2            0            0            1  
3                  1            2            1            2  
4                  1            0            1            1  

[5 rows x 33 columns]


por_df_final columns: 33


school  sex age_category  address  famsize  Pstatus  Medu  Fedu     Mjob  \
0       0    0            1        0        1        0     4     4  at_home   
1       0    0            0        0        1        1     1     1  at_home   
2       0    0            0        0        0        1     1     1  at_home   
3       0    0            0        0        1        1     4     2   health   
4       0    0            0        0        1        1     3     3    other   

       Fjob  ... famrel freetime  goout  Dalc  Walc  health  \
0   teacher  ...      4        3      4     1     1       3   
1     other  ...      5        3      3     1     1       3   
2     other  ...      4        3      2     2     3       3   
3  services  ...      3        2      2     1     1       5   
4     other  ...      4        3      2     1     2       5   

   absences_category  G1_category  G2_category  G3_category  
0                  1            0            1            1  
1                  1            0            1            1  
2                  2            1            1            1  
3                  0            1            1            1  
4                  0            1            1            1  

[5 rows x 33 columns]

In [13]:
display(mat_df_processed['Mjob'].unique())
display(mat_df_processed['Fjob'].unique())
display(mat_df_processed['reason'].unique())
display(mat_df_processed['guardian'].unique())

array(['at_home', 'health', 'other', 'services', 'teacher'], dtype=object)

array(['teacher', 'other', 'services', 'health', 'at_home'], dtype=object)

array(['course', 'other', 'home', 'reputation'], dtype=object)

array(['mother', 'father', 'other'], dtype=object)

In [14]:
nominal_columns = ['Mjob', 'Fjob', 'reason', 'guardian']

# Unify Mjob and Fjob mappings
all_mjob_values = mat_df['Mjob'].unique().tolist() + por_df['Mjob'].unique().tolist()
all_fjob_values = mat_df['Fjob'].unique().tolist() + por_df['Fjob'].unique().tolist()

all_job_types = sorted(list(set(all_mjob_values + all_fjob_values)))
job_mapping = {job: i for i, job in enumerate(all_job_types)}

mat_df_final['Mjob'] = mat_df_final['Mjob'].map(job_mapping)
por_df_final['Mjob'] = por_df_final['Mjob'].map(job_mapping)
mat_df_final['Fjob'] = mat_df_final['Fjob'].map(job_mapping)
por_df_final['Fjob'] = por_df_final['Fjob'].map(job_mapping)

# 'reason' column
all_reason_values = sorted(list(set(mat_df['reason'].unique().tolist() + por_df['reason'].unique().tolist())))
reason_mapping = {reason: i for i, reason in enumerate(all_reason_values)}
mat_df_final['reason'] = mat_df_final['reason'].map(reason_mapping)
por_df_final['reason'] = por_df_final['reason'].map(reason_mapping)

# 'guardian' column
all_guardian_values = sorted(list(set(mat_df['guardian'].unique().tolist() + por_df['guardian'].unique().tolist())))
guardian_mapping = {guardian: i for i, guardian in enumerate(all_guardian_values)}
mat_df_final['guardian'] = mat_df_final['guardian'].map(guardian_mapping)
por_df_final['guardian'] = por_df_final['guardian'].map(guardian_mapping)

print("mat_df_final with encoded nominal columns:")
display(mat_df_final[nominal_columns].head())

print("\npor_df_final with encoded nominal columns:")
display(por_df_final[nominal_columns].head())

mat_df_final with encoded nominal columns:


Mjob  Fjob  reason  guardian
0     0     4       0         1
1     0     2       0         0
2     0     2       2         1
3     1     3       1         1
4     2     2       1         0


por_df_final with encoded nominal columns:


Mjob  Fjob  reason  guardian
0     0     4       0         1
1     0     2       0         0
2     0     2       2         1
3     1     3       1         1
4     2     2       1         0

In [15]:
display(mat_df_processed['Mjob'].unique())
display(mat_df_processed['Fjob'].unique())
display(mat_df_processed['reason'].unique())
display(mat_df_processed['guardian'].unique())

array(['at_home', 'health', 'other', 'services', 'teacher'], dtype=object)

array(['teacher', 'other', 'services', 'health', 'at_home'], dtype=object)

array(['course', 'other', 'home', 'reputation'], dtype=object)

array(['mother', 'father', 'other'], dtype=object)

In [16]:
display(mat_df_final['Mjob'].unique())
display(mat_df_final['Fjob'].unique())
display(mat_df_final['reason'].unique())
display(mat_df_final['guardian'].unique())

# Mjob & Fjob columns:
# at_home: 0
# health: 1
# other: 2
# services: 3
# teacher: 4

# Reason column:
# course: 0
# home: 1
# other: 2
# reputation: 3

# Guardian column:
# father: 0
# mother: 1
# other: 2

array([0, 1, 2, 3, 4])

array([4, 2, 3, 1, 0])

array([0, 2, 1, 3])

array([1, 0, 2])

In [17]:
display(mat_df_final)
display(por_df_final)

school  sex age_category  address  famsize  Pstatus  Medu  Fedu  Mjob  \
0         0    0            1        0        1        0     4     4     0   
1         0    0            0        0        1        1     1     1     0   
2         0    0            0        0        0        1     1     1     0   
3         0    0            0        0        1        1     4     2     1   
4         0    0            0        0        1        1     3     3     2   
..      ...  ...          ...      ...      ...      ...   ...   ...   ...   
390       1    1            1        0        0        0     2     2     3   
391       1    1            0        0        0        1     3     1     3   
392       1    1            1        1        1        1     1     1     2   
393       1    1            1        1        0        1     3     2     3   
394       1    1            1        0        0        1     1     1     2   

     Fjob  ...  famrel  freetime  goout  Dalc  Walc  health  \
0       4  ...       4         3      4     1     1       3   
1       2  ...       5         3      3     1     1       3   
2       2  ...       4         3      2     2     3       3   
3       3  ...       3         2      2     1     1       5   
4       2  ...       4         3      2     1     2       5   
..    ...  ...     ...       ...    ...   ...   ...     ...   
390     3  ...       5         5      4     4     5       4   
391     3  ...       2         4      5     3     4       2   
392     2  ...       5         5      3     3     3       3   
393     2  ...       4         4      1     3     4       5   
394     0  ...       3         2      3     3     3       5   

     absences_category  G1_category  G2_category  G3_category  
0                    2            0            0            0  
1                    1            0            0            0  
2                    2            0            0            1  
3                    1            2            1            2  
4                    1            0            1            1  
..                 ...          ...          ...          ...  
390                  2            0            0            0  
391                  1            1            2            2  
392                  1            1            0            0  
393                  0            1            1            1  
394                  1            0            0            0  

[395 rows x 33 columns]

school  sex age_category  address  famsize  Pstatus  Medu  Fedu  Mjob  \
0         0    0            1        0        1        0     4     4     0   
1         0    0            0        0        1        1     1     1     0   
2         0    0            0        0        0        1     1     1     0   
3         0    0            0        0        1        1     4     2     1   
4         0    0            0        0        1        1     3     3     2   
..      ...  ...          ...      ...      ...      ...   ...   ...   ...   
644       1    0            1        1        1        1     2     3     3   
645       1    0            1        0        0        1     3     1     4   
646       1    0            1        0        1        1     1     1     2   
647       1    1            0        0        0        1     3     1     3   
648       1    1            1        1        0        1     3     2     3   

     Fjob  ...  famrel  freetime  goout  Dalc  Walc  health  \
0       4  ...       4         3      4     1     1       3   
1       2  ...       5         3      3     1     1       3   
2       2  ...       4         3      2     2     3       3   
3       3  ...       3         2      2     1     1       5   
4       2  ...       4         3      2     1     2       5   
..    ...  ...     ...       ...    ...   ...   ...     ...   
644     2  ...       5         4      2     1     2       5   
645     3  ...       4         3      4     1     1       1   
646     2  ...       1         1      1     1     1       5   
647     3  ...       2         4      5     3     4       2   
648     2  ...       4         4      1     3     4       5   

     absences_category  G1_category  G2_category  G3_category  
0                    1            0            1            1  
1                    1            0            1            1  
2                    2            1            1            1  
3                    0            1            1            1  
4                    0            1            1            1  
..                 ...          ...          ...          ...  
644                  1            1            1            1  
645                  1            2            2            2  
646                  2            1            1            0  
647                  2            1            1            1  
648                  1            1            1            1  

[649 rows x 33 columns]

In [18]:
display(mat_df_final.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype   
---  ------             --------------  -----   
 0   school             395 non-null    int64   
 1   sex                395 non-null    int64   
 2   age_category       395 non-null    category
 3   address            395 non-null    int64   
 4   famsize            395 non-null    int64   
 5   Pstatus            395 non-null    int64   
 6   Medu               395 non-null    int64   
 7   Fedu               395 non-null    int64   
 8   Mjob               395 non-null    int64   
 9   Fjob               395 non-null    int64   
 10  reason             395 non-null    int64   
 11  guardian           395 non-null    int64   
 12  traveltime         395 non-null    int64   
 13  studytime          395 non-null    int64   
 14  failures           395 non-null    int64   
 15  schoolsup          395 non-null    int64   
 16  famsup  

None

In [19]:
display(por_df_final.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype   
---  ------             --------------  -----   
 0   school             649 non-null    int64   
 1   sex                649 non-null    int64   
 2   age_category       649 non-null    category
 3   address            649 non-null    int64   
 4   famsize            649 non-null    int64   
 5   Pstatus            649 non-null    int64   
 6   Medu               649 non-null    int64   
 7   Fedu               649 non-null    int64   
 8   Mjob               649 non-null    int64   
 9   Fjob               649 non-null    int64   
 10  reason             649 non-null    int64   
 11  guardian           649 non-null    int64   
 12  traveltime         649 non-null    int64   
 13  studytime          649 non-null    int64   
 14  failures           649 non-null    int64   
 15  schoolsup          649 non-null    int64   
 16  famsup  

None

In [20]:
df_combined = pd.concat([mat_df_final, por_df_final], ignore_index=True)
display(df_combined)

school  sex age_category  address  famsize  Pstatus  Medu  Fedu  Mjob  \
0          0    0            1        0        1        0     4     4     0   
1          0    0            0        0        1        1     1     1     0   
2          0    0            0        0        0        1     1     1     0   
3          0    0            0        0        1        1     4     2     1   
4          0    0            0        0        1        1     3     3     2   
...      ...  ...          ...      ...      ...      ...   ...   ...   ...   
1039       1    0            1        1        1        1     2     3     3   
1040       1    0            1        0        0        1     3     1     4   
1041       1    0            1        0        1        1     1     1     2   
1042       1    1            0        0        0        1     3     1     3   
1043       1    1            1        1        0        1     3     2     3   

      Fjob  ...  famrel  freetime  goout  Dalc  Walc  health  \
0        4  ...       4         3      4     1     1       3   
1        2  ...       5         3      3     1     1       3   
2        2  ...       4         3      2     2     3       3   
3        3  ...       3         2      2     1     1       5   
4        2  ...       4         3      2     1     2       5   
...    ...  ...     ...       ...    ...   ...   ...     ...   
1039     2  ...       5         4      2     1     2       5   
1040     3  ...       4         3      4     1     1       1   
1041     2  ...       1         1      1     1     1       5   
1042     3  ...       2         4      5     3     4       2   
1043     2  ...       4         4      1     3     4       5   

      absences_category  G1_category  G2_category  G3_category  
0                     2            0            0            0  
1                     1            0            0            0  
2                     2            0            0            1  
3                     1            2            1            2  
4                     1            0            1            1  
...                 ...          ...          ...          ...  
1039                  1            1            1            1  
1040                  1            2            2            2  
1041                  2            1            1            0  
1042                  2            1            1            1  
1043                  1            1            1            1  

[1044 rows x 33 columns]

In [21]:
df_combined.to_csv('/content/drive/MyDrive/CSE_250A_final_project/data_processing/mat_por_df_combined.csv', index=False)

### Internal factor & outernal factor

In [22]:
internal_factors = ['studytime', 'failures', 'absences_category', 'higher']
internal_factors_df = df_combined[internal_factors + ['G3_category']]
display(internal_factors_df.head())
internal_factors_df.info()
internal_factors_df.to_csv('/content/drive/MyDrive/CSE_250A_final_project/data_processing/internal_factors_df.csv', index=False)

studytime  failures absences_category  higher G3_category
0          2         0                 2       1           0
1          2         0                 1       1           0
2          2         3                 2       1           1
3          3         0                 1       1           2
4          2         0                 1       1           1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1044 entries, 0 to 1043
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype   
---  ------             --------------  -----   
 0   studytime          1044 non-null   int64   
 1   failures           1044 non-null   int64   
 2   absences_category  1044 non-null   category
 3   higher             1044 non-null   int64   
 4   G3_category        1044 non-null   category
dtypes: category(2), int64(3)
memory usage: 27.0 KB


In [23]:
external_factors = ['Medu', 'famrel', 'internet', 'traveltime']
external_factors_df = df_combined[external_factors + ['G3_category']]
display(external_factors_df.head())
external_factors_df.info()
external_factors_df.to_csv('/content/drive/MyDrive/CSE_250A_final_project/data_processing/external_factors_df.csv', index=False)

Medu  famrel  internet  traveltime G3_category
0     4       4         0           2           0
1     1       5         1           1           0
2     1       4         1           1           1
3     4       3         1           1           2
4     3       4         0           1           1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1044 entries, 0 to 1043
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   Medu         1044 non-null   int64   
 1   famrel       1044 non-null   int64   
 2   internet     1044 non-null   int64   
 3   traveltime   1044 non-null   int64   
 4   G3_category  1044 non-null   category
dtypes: category(1), int64(4)
memory usage: 33.9 KB


### check df_combined with first 5 rows and corresponding columns


In [26]:
# mat_df_final
pd.set_option('display.max_columns', None)
display(mat_df_final.head())

school  sex age_category  address  famsize  Pstatus  Medu  Fedu  Mjob  \
0       0    0            1        0        1        0     4     4     0   
1       0    0            0        0        1        1     1     1     0   
2       0    0            0        0        0        1     1     1     0   
3       0    0            0        0        1        1     4     2     1   
4       0    0            0        0        1        1     3     3     2   

   Fjob  reason  guardian  traveltime  studytime  failures  schoolsup  famsup  \
0     4       0         1           2          2         0          1       0   
1     2       0         0           1          2         0          0       1   
2     2       2         1           1          2         3          1       0   
3     3       1         1           1          3         0          0       1   
4     2       1         0           1          2         0          0       1   

   paid  activities  nursery  higher  internet  romantic  famrel  freetime  \
0     0           0        1       1         0         0       4         3   
1     0           0        0       1         1         0       5         3   
2     1           0        1       1         1         0       4         3   
3     1           1        1       1         1         1       3         2   
4     1           0        1       1         0         0       4         3   

   goout  Dalc  Walc  health absences_category G1_category G2_category  \
0      4     1     1       3                 2           0           0   
1      3     1     1       3                 1           0           0   
2      2     2     3       3                 2           0           0   
3      2     1     1       5                 1           2           1   
4      2     1     2       5                 1           0           1   

  G3_category  
0           0  
1           0  
2           1  
3           2  
4           1

In [25]:
pd.set_option('display.max_columns', None)
display(df_combined.head())

school  sex age_category  address  famsize  Pstatus  Medu  Fedu  Mjob  \
0       0    0            1        0        1        0     4     4     0   
1       0    0            0        0        1        1     1     1     0   
2       0    0            0        0        0        1     1     1     0   
3       0    0            0        0        1        1     4     2     1   
4       0    0            0        0        1        1     3     3     2   

   Fjob  reason  guardian  traveltime  studytime  failures  schoolsup  famsup  \
0     4       0         1           2          2         0          1       0   
1     2       0         0           1          2         0          0       1   
2     2       2         1           1          2         3          1       0   
3     3       1         1           1          3         0          0       1   
4     2       1         0           1          2         0          0       1   

   paid  activities  nursery  higher  internet  romantic  famrel  freetime  \
0     0           0        1       1         0         0       4         3   
1     0           0        0       1         1         0       5         3   
2     1           0        1       1         1         0       4         3   
3     1           1        1       1         1         1       3         2   
4     1           0        1       1         0         0       4         3   

   goout  Dalc  Walc  health absences_category G1_category G2_category  \
0      4     1     1       3                 2           0           0   
1      3     1     1       3                 1           0           0   
2      2     2     3       3                 2           0           0   
3      2     1     1       5                 1           2           1   
4      2     1     2       5                 1           0           1   

  G3_category  
0           0  
1           0  
2           1  
3           2  
4           1

In [27]:
pd.set_option('display.max_columns', None)
display(mat_df.head())

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher   
1     GP   F   17       U     GT3       T     1     1  at_home     other   
2     GP   F   15       U     LE3       T     1     1  at_home     other   
3     GP   F   15       U     GT3       T     4     2   health  services   
4     GP   F   16       U     GT3       T     3     3    other     other   

   reason guardian  traveltime  studytime  failures schoolsup famsup paid  \
0  course   mother           2          2         0       yes     no   no   
1  course   father           1          2         0        no    yes   no   
2   other   mother           1          2         3       yes     no  yes   
3    home   mother           1          3         0        no    yes  yes   
4    home   father           1          2         0        no    yes  yes   

  activities nursery higher internet romantic  famrel  freetime  goout  Dalc  \
0         no     yes    yes       no       no       4         3      4     1   
1         no      no    yes      yes       no       5         3      3     1   
2         no     yes    yes      yes       no       4         3      2     2   
3        yes     yes    yes      yes      yes       3         2      2     1   
4         no     yes    yes       no       no       4         3      2     1   

   Walc  health  absences  G1  G2  G3  
0     1       3         6   5   6   6  
1     1       3         4   5   5   6  
2     3       3        10   7   8  10  
3     1       5         2  15  14  15  
4     2       5         4   6  10  10

In [ ]:
# Columns kept as original: Medu, Fedu, traveltime, studytime, failures, famrel, freetime, goout, Dalc, Walc, health
